name: Release Helm Chart

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Debug directory structure
      - name: Debug directory structure
        run: |
          echo "Current directory:"
          pwd
          echo "Files in current directory:"
          ls -R

      # 3. Package Helm Chart
      - name: Package Helm Chart
        run: |
          helm package .  # Memaketkan chart dari root direktori
          mkdir -p charts  # Membuat direktori 'charts/' jika belum ada
          mv *.tgz charts/  # Memindahkan file .tgz ke direktori 'charts/'

      # 4. Generate index.yaml
      - name: Generate index.yaml
        run: |
          helm repo index charts --url https://frengkysorituamanurung.github.io/helm-chart-v2/
      
      # 5. Commit and Push Changes
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add charts/
          git commit -m "ci: update index.yaml and release Helm chart"
          git push origin main

      - name: Create Tag
        id: create_tag
        run: |
          VERSION="v0.1.$(date +%s)"
          echo "Tag: $VERSION"
          git tag -a $VERSION -m "Release $VERSION"
          git push origin $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: charts/*.tgz
          tag: ${{ steps.create_tag.outputs.VERSION }}
          name: "Helm Chart Release ${{ steps.create_tag.outputs.VERSION }}"
          token: ${{ secrets.GITHUB_TOKEN }}
        
